### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by coheigea** [comment]
@elecharny Yeah I created this Pr to test. It seems to run the steps sequentially, but it's quite fast. The build fails on Java 

Error:  Failed to execute goal org.codehaus.mojo:antlr-maven-plugin:2.2:generate (default) on project api-ldap-model: Execution default of goal org.codehaus.mojo:antlr-maven-plugin:2.2:generate failed: The Security Manager is deprecated and will be removed in a future release -> [Help 1]

**Comment by coheigea** [comment]
you can achieve parallel execution apparently by just having a separate job, rather than testing them all as steps in the same job.

**Comment by elecharny** [comment]
Seems like the maven antlr plugin uses the Security Manager, which has now been deprecated...
We have few options:
- Bump up to antlr4 and see if it plays better with Java 20
- don't build with Java 20 until the problem is solved on maven side
We are not alone here: https://community.jenkins.io/t/error-failed-to-execute-goal-org-codehaus-mojo2-2-generate-cron-on-project-jenkins-core-execution-cron-of-goal-org-codehaus-mojo2-2-generate-failed/3368

**Comment by coheigea** [comment]
@elecharny I got the builds working in parallel now. Would there be much work involved in migrating to antlr4?

**Comment by elecharny** [comment]
Indeed, yes.
Antlr4 is a very different beast, where the lexer is handled like a parser. There are antlr2 construuction that aren't easily converted to antlr4.

OTOH, antlr2 is pretty much dead now, and I think it worth the effort to migrate to antlr4. I think it's a matter of a couple of weeks to get all the grammars translated, including the time it takes to understand the evolution between 2 and 4.

**Comment by elecharny** [comment]
Otherwise, this is great to have all the java versions running ! We probably have to do the same thing for the other projects.

The question would be to know if we should continue using builds.apache.org ?

**Comment by elecharny** [comment]
@coheigea FTR, I have migrated one grammar to antlr4. Not sure it works, but at least it generates the Java code. It's not *that* complex, but I expect some issues while running tests.

**Comment by coheigea** [comment]
Cool @elecharny , I suggest creating a new PR with it so that the tests can run? I'm going to close this PR, as it proves the builds are working OK.

**Comment by elecharny** [comment]
It's not ready yet. I have some issue with the antlr4 maven plugin which does not generate the java code in the proper package (you have to define the outputDirectory parameter in the pom, which is pretty dumb, as you can only generate code in one single package. Does not work well with LDAP API, we have 3 .g4 files in 2 different packages...)

**Pull request closed without merging**
